import Navbar from "./components/Navbar"
import "../../../globals.css"
import ChatbotToggle from "./components/ChatbotToggle"

export const metadata = {
  title: 'ChurchConnect',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {




  return (
    <html lang="en">
      <body>
        <div className="flex flex-col min-h-screen   ">
          <Navbar />
          <main className="grow bg-[#FFE4A2] py-2 ">
            {children}
            <ChatbotToggle />
          </main>
          
        </div>
      </body>
    </html>
  )
}
