import Navbar from "./components/Navbar"
import "@/app/globals.css"

export const metadata = {
  title: 'ChurchConnect Admin',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col min-h-screen   ">
          <Navbar />
          <main className="grow bg-[#FFE4A2] py-2 ">
            {children}
          </main>
          
        </div>

      </body>
    </html>
  )
}
